#spring.application.name=rag-ai
spring:
  application:
    name: rag-ai

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 3014
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: true
    properties:
      hibernate:
        default_schema: ragai
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small   # 1536-dim
    vectorstore:
      pgvector:
        schema-name: ragai
        table-name: vector_store
        initialize-schema: true

rag:
  ingestion:
    on-startup: true
    paths: classpath:/docs/*.pdf
    chunk:
      size: 400
      overlap: 40